import { ApolloWrapper } from "@/lib/apollo-wrapper";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutProps) {
  {
    return (
      <html lang="en">
        <body>
          <div
            style={{
              maxWidth: 960,
              margin: "0 auto",
            }}
          >
            <ApolloWrapper>{children}</ApolloWrapper>
          </div>
        </body>
      </html>
    );
  }
}
